// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bio01_cpp
NumericVector bio01_cpp(NumericMatrix tas);
RcppExport SEXP _rxbioclim_bio01_cpp(SEXP tasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    rcpp_result_gen = Rcpp::wrap(bio01_cpp(tas));
    return rcpp_result_gen;
END_RCPP
}
// bio02_cpp
NumericVector bio02_cpp(NumericMatrix tasmax, NumericMatrix tasmin);
RcppExport SEXP _rxbioclim_bio02_cpp(SEXP tasmaxSEXP, SEXP tasminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    rcpp_result_gen = Rcpp::wrap(bio02_cpp(tasmax, tasmin));
    return rcpp_result_gen;
END_RCPP
}
// bio03_cpp
NumericVector bio03_cpp(NumericMatrix tasmax, NumericMatrix tasmin);
RcppExport SEXP _rxbioclim_bio03_cpp(SEXP tasmaxSEXP, SEXP tasminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    rcpp_result_gen = Rcpp::wrap(bio03_cpp(tasmax, tasmin));
    return rcpp_result_gen;
END_RCPP
}
// bio04_cpp
NumericVector bio04_cpp(NumericMatrix tas);
RcppExport SEXP _rxbioclim_bio04_cpp(SEXP tasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    rcpp_result_gen = Rcpp::wrap(bio04_cpp(tas));
    return rcpp_result_gen;
END_RCPP
}
// bio05_cpp
NumericVector bio05_cpp(NumericMatrix tasmax);
RcppExport SEXP _rxbioclim_bio05_cpp(SEXP tasmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(bio05_cpp(tasmax));
    return rcpp_result_gen;
END_RCPP
}
// bio06_cpp
NumericVector bio06_cpp(NumericMatrix tasmin);
RcppExport SEXP _rxbioclim_bio06_cpp(SEXP tasminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    rcpp_result_gen = Rcpp::wrap(bio06_cpp(tasmin));
    return rcpp_result_gen;
END_RCPP
}
// bio07_cpp
NumericVector bio07_cpp(NumericMatrix tasmax, NumericMatrix tasmin);
RcppExport SEXP _rxbioclim_bio07_cpp(SEXP tasmaxSEXP, SEXP tasminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    rcpp_result_gen = Rcpp::wrap(bio07_cpp(tasmax, tasmin));
    return rcpp_result_gen;
END_RCPP
}
// bio08_cpp
NumericVector bio08_cpp(NumericMatrix tas, NumericMatrix pr);
RcppExport SEXP _rxbioclim_bio08_cpp(SEXP tasSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio08_cpp(tas, pr));
    return rcpp_result_gen;
END_RCPP
}
// bio09_cpp
NumericVector bio09_cpp(NumericMatrix tas, NumericMatrix pr);
RcppExport SEXP _rxbioclim_bio09_cpp(SEXP tasSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio09_cpp(tas, pr));
    return rcpp_result_gen;
END_RCPP
}
// bio10_cpp
NumericVector bio10_cpp(NumericMatrix tas);
RcppExport SEXP _rxbioclim_bio10_cpp(SEXP tasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    rcpp_result_gen = Rcpp::wrap(bio10_cpp(tas));
    return rcpp_result_gen;
END_RCPP
}
// bio11_cpp
NumericVector bio11_cpp(NumericMatrix tas);
RcppExport SEXP _rxbioclim_bio11_cpp(SEXP tasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    rcpp_result_gen = Rcpp::wrap(bio11_cpp(tas));
    return rcpp_result_gen;
END_RCPP
}
// bio12_cpp
NumericVector bio12_cpp(NumericMatrix pr);
RcppExport SEXP _rxbioclim_bio12_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio12_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio13_cpp
NumericVector bio13_cpp(NumericMatrix pr);
RcppExport SEXP _rxbioclim_bio13_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio13_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio14_cpp
NumericVector bio14_cpp(NumericMatrix pr);
RcppExport SEXP _rxbioclim_bio14_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio14_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio15_cpp
NumericVector bio15_cpp(NumericMatrix pr);
RcppExport SEXP _rxbioclim_bio15_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio15_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio16_cpp
NumericVector bio16_cpp(NumericMatrix pr);
RcppExport SEXP _rxbioclim_bio16_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio16_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio17_cpp
NumericVector bio17_cpp(NumericMatrix pr);
RcppExport SEXP _rxbioclim_bio17_cpp(SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio17_cpp(pr));
    return rcpp_result_gen;
END_RCPP
}
// bio18_cpp
NumericVector bio18_cpp(NumericMatrix tas, NumericMatrix pr);
RcppExport SEXP _rxbioclim_bio18_cpp(SEXP tasSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio18_cpp(tas, pr));
    return rcpp_result_gen;
END_RCPP
}
// bio19_cpp
NumericVector bio19_cpp(NumericMatrix tas, NumericMatrix pr);
RcppExport SEXP _rxbioclim_bio19_cpp(SEXP tasSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bio19_cpp(tas, pr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_cpp
NumericMatrix bioclim_cpp(NumericMatrix tas, NumericMatrix tasmax, NumericMatrix tasmin, NumericMatrix pr);
RcppExport SEXP _rxbioclim_bioclim_cpp(SEXP tasSEXP, SEXP tasmaxSEXP, SEXP tasminSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tasmin(tasminSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_cpp(tas, tasmax, tasmin, pr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rxbioclim_bio01_cpp", (DL_FUNC) &_rxbioclim_bio01_cpp, 1},
    {"_rxbioclim_bio02_cpp", (DL_FUNC) &_rxbioclim_bio02_cpp, 2},
    {"_rxbioclim_bio03_cpp", (DL_FUNC) &_rxbioclim_bio03_cpp, 2},
    {"_rxbioclim_bio04_cpp", (DL_FUNC) &_rxbioclim_bio04_cpp, 1},
    {"_rxbioclim_bio05_cpp", (DL_FUNC) &_rxbioclim_bio05_cpp, 1},
    {"_rxbioclim_bio06_cpp", (DL_FUNC) &_rxbioclim_bio06_cpp, 1},
    {"_rxbioclim_bio07_cpp", (DL_FUNC) &_rxbioclim_bio07_cpp, 2},
    {"_rxbioclim_bio08_cpp", (DL_FUNC) &_rxbioclim_bio08_cpp, 2},
    {"_rxbioclim_bio09_cpp", (DL_FUNC) &_rxbioclim_bio09_cpp, 2},
    {"_rxbioclim_bio10_cpp", (DL_FUNC) &_rxbioclim_bio10_cpp, 1},
    {"_rxbioclim_bio11_cpp", (DL_FUNC) &_rxbioclim_bio11_cpp, 1},
    {"_rxbioclim_bio12_cpp", (DL_FUNC) &_rxbioclim_bio12_cpp, 1},
    {"_rxbioclim_bio13_cpp", (DL_FUNC) &_rxbioclim_bio13_cpp, 1},
    {"_rxbioclim_bio14_cpp", (DL_FUNC) &_rxbioclim_bio14_cpp, 1},
    {"_rxbioclim_bio15_cpp", (DL_FUNC) &_rxbioclim_bio15_cpp, 1},
    {"_rxbioclim_bio16_cpp", (DL_FUNC) &_rxbioclim_bio16_cpp, 1},
    {"_rxbioclim_bio17_cpp", (DL_FUNC) &_rxbioclim_bio17_cpp, 1},
    {"_rxbioclim_bio18_cpp", (DL_FUNC) &_rxbioclim_bio18_cpp, 2},
    {"_rxbioclim_bio19_cpp", (DL_FUNC) &_rxbioclim_bio19_cpp, 2},
    {"_rxbioclim_bioclim_cpp", (DL_FUNC) &_rxbioclim_bioclim_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rxbioclim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
