// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bioclim_model_new
SEXP bioclim_model_new(Rcpp::NumericVector tas, Rcpp::NumericVector tasmax, Rcpp::NumericVector tasmin, Rcpp::NumericVector pr);
RcppExport SEXP _rxbioclim_bioclim_model_new(SEXP tasSEXP, SEXP tasmaxSEXP, SEXP tasminSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tas(tasSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tasmax(tasmaxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tasmin(tasminSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_new(tas, tasmax, tasmin, pr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_is_null
bool bioclim_model_is_null(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_is_null(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_is_null(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio01
double bioclim_model_bio01(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio01(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio01(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio02
double bioclim_model_bio02(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio02(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio02(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio03
double bioclim_model_bio03(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio03(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio03(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio04
double bioclim_model_bio04(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio04(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio04(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio05
double bioclim_model_bio05(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio05(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio05(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio06
double bioclim_model_bio06(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio06(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio06(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio07
double bioclim_model_bio07(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio07(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio07(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio08
double bioclim_model_bio08(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio08(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio08(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio09
double bioclim_model_bio09(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio09(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio09(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio10
double bioclim_model_bio10(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio10(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio10(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio11
double bioclim_model_bio11(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio11(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio11(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio12
double bioclim_model_bio12(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio12(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio12(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio13
double bioclim_model_bio13(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio13(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio13(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio14
double bioclim_model_bio14(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio14(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio14(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio15
double bioclim_model_bio15(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio15(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio15(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio16
double bioclim_model_bio16(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio16(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio16(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio17
double bioclim_model_bio17(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio17(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio17(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio18
double bioclim_model_bio18(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio18(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio18(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_bio19
double bioclim_model_bio19(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_bio19(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_bio19(ptr));
    return rcpp_result_gen;
END_RCPP
}
// bioclim_model_compute
Rcpp::NumericVector bioclim_model_compute(SEXP ptr);
RcppExport SEXP _rxbioclim_bioclim_model_compute(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(bioclim_model_compute(ptr));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_bioclim_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rxbioclim_bioclim_model_new", (DL_FUNC) &_rxbioclim_bioclim_model_new, 4},
    {"_rxbioclim_bioclim_model_is_null", (DL_FUNC) &_rxbioclim_bioclim_model_is_null, 1},
    {"_rxbioclim_bioclim_model_bio01", (DL_FUNC) &_rxbioclim_bioclim_model_bio01, 1},
    {"_rxbioclim_bioclim_model_bio02", (DL_FUNC) &_rxbioclim_bioclim_model_bio02, 1},
    {"_rxbioclim_bioclim_model_bio03", (DL_FUNC) &_rxbioclim_bioclim_model_bio03, 1},
    {"_rxbioclim_bioclim_model_bio04", (DL_FUNC) &_rxbioclim_bioclim_model_bio04, 1},
    {"_rxbioclim_bioclim_model_bio05", (DL_FUNC) &_rxbioclim_bioclim_model_bio05, 1},
    {"_rxbioclim_bioclim_model_bio06", (DL_FUNC) &_rxbioclim_bioclim_model_bio06, 1},
    {"_rxbioclim_bioclim_model_bio07", (DL_FUNC) &_rxbioclim_bioclim_model_bio07, 1},
    {"_rxbioclim_bioclim_model_bio08", (DL_FUNC) &_rxbioclim_bioclim_model_bio08, 1},
    {"_rxbioclim_bioclim_model_bio09", (DL_FUNC) &_rxbioclim_bioclim_model_bio09, 1},
    {"_rxbioclim_bioclim_model_bio10", (DL_FUNC) &_rxbioclim_bioclim_model_bio10, 1},
    {"_rxbioclim_bioclim_model_bio11", (DL_FUNC) &_rxbioclim_bioclim_model_bio11, 1},
    {"_rxbioclim_bioclim_model_bio12", (DL_FUNC) &_rxbioclim_bioclim_model_bio12, 1},
    {"_rxbioclim_bioclim_model_bio13", (DL_FUNC) &_rxbioclim_bioclim_model_bio13, 1},
    {"_rxbioclim_bioclim_model_bio14", (DL_FUNC) &_rxbioclim_bioclim_model_bio14, 1},
    {"_rxbioclim_bioclim_model_bio15", (DL_FUNC) &_rxbioclim_bioclim_model_bio15, 1},
    {"_rxbioclim_bioclim_model_bio16", (DL_FUNC) &_rxbioclim_bioclim_model_bio16, 1},
    {"_rxbioclim_bioclim_model_bio17", (DL_FUNC) &_rxbioclim_bioclim_model_bio17, 1},
    {"_rxbioclim_bioclim_model_bio18", (DL_FUNC) &_rxbioclim_bioclim_model_bio18, 1},
    {"_rxbioclim_bioclim_model_bio19", (DL_FUNC) &_rxbioclim_bioclim_model_bio19, 1},
    {"_rxbioclim_bioclim_model_compute", (DL_FUNC) &_rxbioclim_bioclim_model_compute, 1},
    {"_rcpp_module_boot_bioclim_mod", (DL_FUNC) &_rcpp_module_boot_bioclim_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rxbioclim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
