# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute BIO01 (Mean Annual Temperature) for a raster block
#'
#' @param tas Numeric matrix with 12 columns (one per month); rows are pixels.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio01_cpp <- function(tas) {
    .Call(`_rxbioclim_bio01_cpp`, tas)
}

#' Compute BIO02 (Mean Diurnal Range) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio02_cpp <- function(tasmax, tasmin) {
    .Call(`_rxbioclim_bio02_cpp`, tasmax, tasmin)
}

#' Compute BIO03 (Isothermality) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel (NaN where BIO07 == 0).
#' @keywords internal
bio03_cpp <- function(tasmax, tasmin) {
    .Call(`_rxbioclim_bio03_cpp`, tasmax, tasmin)
}

#' Compute BIO04 (Temperature Seasonality) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio04_cpp <- function(tas) {
    .Call(`_rxbioclim_bio04_cpp`, tas)
}

#' Compute BIO05 (Max Temperature of Warmest Month) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio05_cpp <- function(tasmax) {
    .Call(`_rxbioclim_bio05_cpp`, tasmax)
}

#' Compute BIO06 (Min Temperature of Coldest Month) for a raster block
#'
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio06_cpp <- function(tasmin) {
    .Call(`_rxbioclim_bio06_cpp`, tasmin)
}

#' Compute BIO07 (Temperature Annual Range) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio07_cpp <- function(tasmax, tasmin) {
    .Call(`_rxbioclim_bio07_cpp`, tasmax, tasmin)
}

#' Compute BIO08 (Mean Temperature of Wettest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio08_cpp <- function(tas, pr) {
    .Call(`_rxbioclim_bio08_cpp`, tas, pr)
}

#' Compute BIO09 (Mean Temperature of Driest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio09_cpp <- function(tas, pr) {
    .Call(`_rxbioclim_bio09_cpp`, tas, pr)
}

#' Compute BIO10 (Mean Temperature of Warmest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio10_cpp <- function(tas) {
    .Call(`_rxbioclim_bio10_cpp`, tas)
}

#' Compute BIO11 (Mean Temperature of Coldest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio11_cpp <- function(tas) {
    .Call(`_rxbioclim_bio11_cpp`, tas)
}

#' Compute BIO12 (Annual Precipitation) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio12_cpp <- function(pr) {
    .Call(`_rxbioclim_bio12_cpp`, pr)
}

#' Compute BIO13 (Precipitation of Wettest Month) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio13_cpp <- function(pr) {
    .Call(`_rxbioclim_bio13_cpp`, pr)
}

#' Compute BIO14 (Precipitation of Driest Month) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio14_cpp <- function(pr) {
    .Call(`_rxbioclim_bio14_cpp`, pr)
}

#' Compute BIO15 (Precipitation Seasonality) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel (NaN where mean precip == 0).
#' @keywords internal
bio15_cpp <- function(pr) {
    .Call(`_rxbioclim_bio15_cpp`, pr)
}

#' Compute BIO16 (Precipitation of Wettest Quarter) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio16_cpp <- function(pr) {
    .Call(`_rxbioclim_bio16_cpp`, pr)
}

#' Compute BIO17 (Precipitation of Driest Quarter) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio17_cpp <- function(pr) {
    .Call(`_rxbioclim_bio17_cpp`, pr)
}

#' Compute BIO18 (Precipitation of Warmest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio18_cpp <- function(tas, pr) {
    .Call(`_rxbioclim_bio18_cpp`, tas, pr)
}

#' Compute BIO19 (Precipitation of Coldest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio19_cpp <- function(tas, pr) {
    .Call(`_rxbioclim_bio19_cpp`, tas, pr)
}

#' Compute all 19 bioclimatic variables for a raster block
#'
#' @param tas    Numeric matrix (pixels x 12): monthly mean temperature.
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @param pr     Numeric matrix (pixels x 12): monthly precipitation.
#' @param ncores Integer: number of OpenMP threads (default 1).
#' @return Numeric matrix (pixels x 19) with one column per variable
#'   (bio01..bio19), named accordingly.
#' @keywords internal
bioclim_cpp <- function(tas, tasmax, tasmin, pr, ncores = 1L) {
    .Call(`_rxbioclim_bioclim_cpp`, tas, tasmax, tasmin, pr, ncores)
}

#' Compute all 19 bioclimatic variables (vectorized, zero-copy bridge)
#'
#' A faster alternative to \code{bioclim_cpp()} that uses whole-array
#' vectorized operations and maps R matrix memory directly onto C++ pointers
#' (zero-copy on both input and output).
#'
#' @param tas    Numeric matrix (n_pixels x 12): monthly mean temperature.
#' @param tasmax Numeric matrix (n_pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (n_pixels x 12): monthly min temperature.
#' @param pr     Numeric matrix (n_pixels x 12): monthly precipitation.
#' @param ncores Integer: number of OpenMP threads (default 1).
#' @return Numeric matrix (n_pixels x 19) with one column per variable
#'   (bio01..bio19), named accordingly.
#' @keywords internal
bioclim_xt <- function(tas, tasmax, tasmin, pr, ncores = 1L) {
    .Call(`_rxbioclim_bioclim_xt`, tas, tasmax, tasmin, pr, ncores)
}

#' Create a new C++ BioclimModel and return an external pointer
#'
#' @param tas    Numeric vector of length 12.
#' @param tasmax Numeric vector of length 12.
#' @param tasmin Numeric vector of length 12.
#' @param pr     Numeric vector of length 12.
#' @return An external pointer wrapping a \code{BioclimModel} C++ object.
#' @keywords internal
bioclim_model_new <- function(tas, tasmax, tasmin, pr) {
    .Call(`_rxbioclim_bioclim_model_new`, tas, tasmax, tasmin, pr)
}

#' Test whether the C++ pointer is null
#' @param ptr An external pointer.
#' @return Logical scalar.
#' @keywords internal
bioclim_model_is_null <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_is_null`, ptr)
}

#' @keywords internal
bioclim_model_bio01 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio01`, ptr)
}

#' @keywords internal
bioclim_model_bio02 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio02`, ptr)
}

#' @keywords internal
bioclim_model_bio03 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio03`, ptr)
}

#' @keywords internal
bioclim_model_bio04 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio04`, ptr)
}

#' @keywords internal
bioclim_model_bio05 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio05`, ptr)
}

#' @keywords internal
bioclim_model_bio06 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio06`, ptr)
}

#' @keywords internal
bioclim_model_bio07 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio07`, ptr)
}

#' @keywords internal
bioclim_model_bio08 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio08`, ptr)
}

#' @keywords internal
bioclim_model_bio09 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio09`, ptr)
}

#' @keywords internal
bioclim_model_bio10 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio10`, ptr)
}

#' @keywords internal
bioclim_model_bio11 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio11`, ptr)
}

#' @keywords internal
bioclim_model_bio12 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio12`, ptr)
}

#' @keywords internal
bioclim_model_bio13 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio13`, ptr)
}

#' @keywords internal
bioclim_model_bio14 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio14`, ptr)
}

#' @keywords internal
bioclim_model_bio15 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio15`, ptr)
}

#' @keywords internal
bioclim_model_bio16 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio16`, ptr)
}

#' @keywords internal
bioclim_model_bio17 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio17`, ptr)
}

#' @keywords internal
bioclim_model_bio18 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio18`, ptr)
}

#' @keywords internal
bioclim_model_bio19 <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_bio19`, ptr)
}

#' Compute all 19 bioclimatic variables from the C++ object
#' @param ptr An external pointer to a \code{BioclimModel} C++ object.
#' @return Named numeric vector of length 19.
#' @keywords internal
bioclim_model_compute <- function(ptr) {
    .Call(`_rxbioclim_bioclim_model_compute`, ptr)
}

#' Check whether GDAL can open a raster file
#'
#' @param path Character string: path to the raster file.
#' @return Logical \code{TRUE} if GDAL can open the file, \code{FALSE}
#'   otherwise.
#' @examples
#' \donttest{
#' # Works only when GDAL is available:
#' gdal_can_open(system.file("extdata", "tiny.tif", package = "rxbioclim"))
#' }
#' @export
gdal_can_open <- function(path) {
    .Call(`_rxbioclim_gdal_can_open`, path)
}

#' Return metadata about a GDAL-readable raster
#'
#' @param path Character string: path to the raster file.
#' @return Named list with nrows, ncols, nbands, geotransform, crs, scale,
#'   offset.
#' @examples
#' \donttest{
#' info <- gdal_info(
#'   system.file("extdata", "tiny.tif", package = "rxbioclim")
#' )
#' str(info)
#' }
#' @export
gdal_info <- function(path) {
    .Call(`_rxbioclim_gdal_info`, path)
}

engine_create <- function() {
    .Call(`_rxbioclim_engine_create`)
}

engine_open <- function(xptr, tas_files, tasmax_files, tasmin_files, pr_files) {
    invisible(.Call(`_rxbioclim_engine_open`, xptr, tas_files, tasmax_files, tasmin_files, pr_files))
}

engine_set_output <- function(xptr, path) {
    invisible(.Call(`_rxbioclim_engine_set_output`, xptr, path))
}

engine_set_mask <- function(xptr, mask_path) {
    invisible(.Call(`_rxbioclim_engine_set_mask`, xptr, mask_path))
}

engine_set_threads <- function(xptr, n) {
    invisible(.Call(`_rxbioclim_engine_set_threads`, xptr, n))
}

#' @keywords internal
engine_set_tile_size <- function(xptr, tile_size) {
    invisible(.Call(`_rxbioclim_engine_set_tile_size`, xptr, tile_size))
}

engine_compute <- function(xptr) {
    .Call(`_rxbioclim_engine_compute`, xptr)
}

#' Rasterize a vector polygon layer to a binary mask raster
#'
#' @param vector_path Character string: path to any OGR-readable vector source.
#' @param ref_raster_path Character string: path to a GDAL-readable raster used
#'   as the spatial reference.
#' @param output_mask_path Character string: file path for the output mask GeoTIFF.
#' @return Invisibly returns \code{NULL}.
#' @seealso \code{\link{create_mask}}, \code{\link{apply_mask_cpp}}
#' @export
rasterize_mask_cpp <- function(vector_path, ref_raster_path, output_mask_path) {
    invisible(.Call(`_rxbioclim_rasterize_mask_cpp`, vector_path, ref_raster_path, output_mask_path))
}

#' Apply a binary mask raster to an input raster
#'
#' @param input_path Character string: path to a GDAL-readable raster.
#' @param mask_path Character string: path to a single-band binary mask raster.
#' @param output_path Character string: file path for the output masked raster.
#' @return Invisibly returns \code{NULL}.
#' @seealso \code{\link{create_mask}}, \code{\link{rasterize_mask_cpp}}
#' @export
apply_mask_cpp <- function(input_path, mask_path, output_path) {
    invisible(.Call(`_rxbioclim_apply_mask_cpp`, input_path, mask_path, output_path))
}