# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute BIO01 (Mean Annual Temperature) for a raster block
#'
#' @param tas Numeric matrix with 12 columns (one per month); rows are pixels.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio01_cpp <- function(tas) {
    .Call('_rxbioclim_bio01_cpp', PACKAGE = 'rxbioclim', tas)
}

#' Compute BIO02 (Mean Diurnal Range) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio02_cpp <- function(tasmax, tasmin) {
    .Call('_rxbioclim_bio02_cpp', PACKAGE = 'rxbioclim', tasmax, tasmin)
}

#' Compute BIO03 (Isothermality) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel (NaN where BIO07 == 0).
#' @keywords internal
bio03_cpp <- function(tasmax, tasmin) {
    .Call('_rxbioclim_bio03_cpp', PACKAGE = 'rxbioclim', tasmax, tasmin)
}

#' Compute BIO04 (Temperature Seasonality) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio04_cpp <- function(tas) {
    .Call('_rxbioclim_bio04_cpp', PACKAGE = 'rxbioclim', tas)
}

#' Compute BIO05 (Max Temperature of Warmest Month) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio05_cpp <- function(tasmax) {
    .Call('_rxbioclim_bio05_cpp', PACKAGE = 'rxbioclim', tasmax)
}

#' Compute BIO06 (Min Temperature of Coldest Month) for a raster block
#'
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio06_cpp <- function(tasmin) {
    .Call('_rxbioclim_bio06_cpp', PACKAGE = 'rxbioclim', tasmin)
}

#' Compute BIO07 (Temperature Annual Range) for a raster block
#'
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio07_cpp <- function(tasmax, tasmin) {
    .Call('_rxbioclim_bio07_cpp', PACKAGE = 'rxbioclim', tasmax, tasmin)
}

#' Compute BIO08 (Mean Temperature of Wettest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio08_cpp <- function(tas, pr) {
    .Call('_rxbioclim_bio08_cpp', PACKAGE = 'rxbioclim', tas, pr)
}

#' Compute BIO09 (Mean Temperature of Driest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio09_cpp <- function(tas, pr) {
    .Call('_rxbioclim_bio09_cpp', PACKAGE = 'rxbioclim', tas, pr)
}

#' Compute BIO10 (Mean Temperature of Warmest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio10_cpp <- function(tas) {
    .Call('_rxbioclim_bio10_cpp', PACKAGE = 'rxbioclim', tas)
}

#' Compute BIO11 (Mean Temperature of Coldest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio11_cpp <- function(tas) {
    .Call('_rxbioclim_bio11_cpp', PACKAGE = 'rxbioclim', tas)
}

#' Compute BIO12 (Annual Precipitation) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio12_cpp <- function(pr) {
    .Call('_rxbioclim_bio12_cpp', PACKAGE = 'rxbioclim', pr)
}

#' Compute BIO13 (Precipitation of Wettest Month) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio13_cpp <- function(pr) {
    .Call('_rxbioclim_bio13_cpp', PACKAGE = 'rxbioclim', pr)
}

#' Compute BIO14 (Precipitation of Driest Month) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio14_cpp <- function(pr) {
    .Call('_rxbioclim_bio14_cpp', PACKAGE = 'rxbioclim', pr)
}

#' Compute BIO15 (Precipitation Seasonality) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel (NaN where mean precip == 0).
#' @keywords internal
bio15_cpp <- function(pr) {
    .Call('_rxbioclim_bio15_cpp', PACKAGE = 'rxbioclim', pr)
}

#' Compute BIO16 (Precipitation of Wettest Quarter) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio16_cpp <- function(pr) {
    .Call('_rxbioclim_bio16_cpp', PACKAGE = 'rxbioclim', pr)
}

#' Compute BIO17 (Precipitation of Driest Quarter) for a raster block
#'
#' @param pr Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio17_cpp <- function(pr) {
    .Call('_rxbioclim_bio17_cpp', PACKAGE = 'rxbioclim', pr)
}

#' Compute BIO18 (Precipitation of Warmest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio18_cpp <- function(tas, pr) {
    .Call('_rxbioclim_bio18_cpp', PACKAGE = 'rxbioclim', tas, pr)
}

#' Compute BIO19 (Precipitation of Coldest Quarter) for a raster block
#'
#' @param tas Numeric matrix (pixels x 12): monthly mean temperature.
#' @param pr  Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric vector with one value per pixel.
#' @keywords internal
bio19_cpp <- function(tas, pr) {
    .Call('_rxbioclim_bio19_cpp', PACKAGE = 'rxbioclim', tas, pr)
}

#' Compute all 19 bioclimatic variables for a raster block
#'
#' @param tas    Numeric matrix (pixels x 12): monthly mean temperature.
#' @param tasmax Numeric matrix (pixels x 12): monthly max temperature.
#' @param tasmin Numeric matrix (pixels x 12): monthly min temperature.
#' @param pr     Numeric matrix (pixels x 12): monthly precipitation.
#' @return Numeric matrix (pixels x 19) with one column per variable
#'   (bio01..bio19), named accordingly.
#' @keywords internal
bioclim_cpp <- function(tas, tasmax, tasmin, pr) {
    .Call('_rxbioclim_bioclim_cpp', PACKAGE = 'rxbioclim', tas, tasmax, tasmin, pr)
}

