# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a new C++ BioclimModel and return an external pointer
#'
#' @param tas    Numeric vector of length 12.
#' @param tasmax Numeric vector of length 12.
#' @param tasmin Numeric vector of length 12.
#' @param pr     Numeric vector of length 12.
#' @return An external pointer wrapping a \code{BioclimModel} C++ object.
#' @keywords internal
bioclim_model_new <- function(tas, tasmax, tasmin, pr) {
    .Call('_rxbioclim_bioclim_model_new', PACKAGE = 'rxbioclim', tas, tasmax, tasmin, pr)
}

#' Test whether the C++ pointer is null
#' @param ptr An external pointer.
#' @return Logical scalar.
#' @keywords internal
bioclim_model_is_null <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_is_null', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio01 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio01', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio02 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio02', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio03 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio03', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio04 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio04', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio05 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio05', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio06 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio06', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio07 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio07', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio08 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio08', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio09 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio09', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio10 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio10', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio11 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio11', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio12 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio12', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio13 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio13', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio14 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio14', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio15 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio15', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio16 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio16', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio17 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio17', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio18 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio18', PACKAGE = 'rxbioclim', ptr)
}

#' @keywords internal
bioclim_model_bio19 <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_bio19', PACKAGE = 'rxbioclim', ptr)
}

#' Compute all 19 bioclimatic variables from the C++ object
#' @param ptr An external pointer to a \code{BioclimModel} C++ object.
#' @return Named numeric vector of length 19.
#' @keywords internal
bioclim_model_compute <- function(ptr) {
    .Call('_rxbioclim_bioclim_model_compute', PACKAGE = 'rxbioclim', ptr)
}

