name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y libomp-dev

    - name: Build
      run: |
        cmake -S . -B build
        cmake --build build
